### ISSUE TITLE
raise_on_save_failure broken when using orm :data_mapper:

### ISSUE THREAD

**Issue by akelagercrantz** [jm81/dm-devise#1]
**To reproduce:**

Use orm :data_mapper:

Assume we have a class Foo using some sort of validation. A new and unchanged foo object is not valid.

```
foo = Foo.new
foo.raise_on_save_failure = true
foo.save
```

_Should have raised an error but simply returns false_

I think the issue is located here: http://github.com/jm81/dm-devise/blob/master/lib/devise/orm/data_mapper/compatibility.rb#L55

Doing a valid check will always return false, never invoking super. Also, perhaps checking validity isn't necessary when not using data_mapper_active_model?

**Comment by jm81** [comment]
Fixed in http://github.com/jm81/dm-devise/commit/ae26aa1f6a102e669381b6669b58fdd3da1cb3e5
Thanks for letting me know!
