### ISSUE TITLE
Could not find generator data_mapper:devise_install

### ISSUE THREAD

**Issue by vsanta** [jm81/dm-devise#18]
Hi,

I'm unable to install devise because I get this error: Could not find generator data_mapper:devise_install

My project is using Rails 3.2 and therefor I'm using most of dm-\* gems using their master branch.

Any ideas?

**Comment by jm81** [comment]
It looks like the generator wasn't loading due to a namespacing issue. I've fixed it in ba26566b . I've also pushed a 2.0.1 gem with that fix and snusnu's updates to the DM dependencies. Please let me know if this fixes it for you.
