### ISSUE TITLE
no such file to load -- devise/orm/datamapper (LoadError)

### ISSUE THREAD

**Issue by rtacconi** [jm81/dm-devise#19]
I am getting this error:

/gems/activesupport-3.2.2/lib/active_support/dependencies.rb:251:in `require': no such file to load -- devise/orm/datamapper (LoadError)

My Gemfile

source 'http://rubygems.org'

RAILS_VERSION = '~> 3.2.0'
DM_VERSION    = '~> 1.2.0'

gem 'activesupport',      RAILS_VERSION, :require => 'active_support'
gem 'actionpack',         RAILS_VERSION, :require => 'action_pack'
gem 'actionmailer',       RAILS_VERSION, :require => 'action_mailer'
gem 'activeresource',     RAILS_VERSION, :require => 'active_resource'
gem 'railties',           RAILS_VERSION, :require => 'rails'
gem 'tzinfo'

gem 'dm-rails',               '~> 1.2.1'
gem 'dm-sqlite-adapter', DM_VERSION

gem 'dm-migrations',        DM_VERSION
gem 'dm-types',             DM_VERSION
gem 'dm-validations',       DM_VERSION
gem 'dm-constraints',       DM_VERSION
gem 'dm-transactions',      DM_VERSION
gem 'dm-aggregates',        DM_VERSION
gem 'dm-timestamps',        DM_VERSION
gem 'dm-observer',          DM_VERSION

gem 'haml'
gem 'dm-devise',         '~> 2.0.1'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'twitter-bootstrap-rails'
  # gem 'therubyracer'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

group :test do
  # Pretty printed test output
  gem 'turn', '~> 0.8.3', :require => false
end

group :test, :development do
  gem "rspec-rails", "~> 2.6"
  gem 'fabrication'
end

**Comment by jm81** [comment]
In config/initializers/devise.rb, check the line "require 'devise/orm/data_mapper'" (near the top). data_mapper should have an underscore in it. That's my first guess, let me know if that's not it.

**Comment by rtacconi** [comment]
I looked into the gem but yes, you are right the require was in config/initializers/devise.rb
