### ISSUE TITLE
Problems w/"new" install 

### ISSUE THREAD

**Issue by dmz006** [jm81/dm-devise#8]
I just installed ruby-1.9.2-p136 and have been fighting my passenger install noticing it wanted dm-devise installed.  I try to install it & get the following error:

gem install dm-devise
ERROR:  Error installing dm-devise:
    dm-devise requires dm-devise (>= 0, runtime)

**Comment by jm81** [comment]
What version of dm-devise?

**Comment by dmz006** [comment]
1.1.6; i found the issue was that it requires that dm-devise requires 1.1.4 and passenger kept saying I needed to "bundle install"; and that and "gem install dm-devise" wouldn't work.

I had to: gem install dm-devise -v 1.1.4
then it worked fine.
