### ISSUE TITLE
Depends on rails 3.0.3 only.

### ISSUE THREAD

**Issue by postmodern** [jm81/dm-devise#9]
I need to upgrade Rails to 3.0.4 (which fixes two major vulnerabilities), but dm-devise appears to depend on `rails = 3.0.3`.

https://github.com/jm81/dm-devise/blob/master/Gemfile#L5
https://github.com/jm81/dm-devise/blob/master/Gemfile.lock#L178
http://rubygems.org/gems/dm-devise

Also the dependencies seem to be listed twice on rubygems.org? How did you release dm-devise 1.1.6?

**Comment by jm81** [comment]
Oops. Thought I had fixed this. The problem is jeweler pulling dependencies from the Gemfile. I'll get it fixed today.

**Comment by postmodern** [comment]
https://github.com/jm81/dm-devise/blob/master/Gemfile#L5-17

These dependencies appear to have been slurped up by Bundler in the release process. They should probably be in a separate group:

```
group :development do
  ....
end
```

**Comment by postmodern** [comment]
Ah I see. What version of Jeweler are you using? I don't seen `jeweler` listed in the Gemfile.

**Comment by jm81** [comment]
1.5.2. I was planning to stop using jeweler for this reason. Defining a development group hadn't occurred to me.

**Comment by postmodern** [comment]
I helped out with Jeweler's Bundler integration, and technicalpickles decided to only slurp in the `:default`, `:runtime` and `:development` groups; every other group is ignored. Also, it's a good idea to never use exact versions in dependencies, always default to using `~> x.y`.

**Comment by postmodern** [comment]
Also, use `Bundler.setup(:default, :development)` in your `Rakefile` to lock-down the versions of Jeweler, RSpec, RDoc, etc.

**Comment by jm81** [comment]
I've release 1.1.8. Hopefully, that fixes it. Thanks for the help.

**Comment by postmodern** [comment]
Worked. Successfully upgraded `dm-devise` to 1.1.8 and `rails` to 3.0.4.

```
bundle update dm-devise actionmailer actionpack activemodel activesupport activerecord railties rails
```
